name: Lint config
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          run_install: true
          version: 9

      - name: lint
        run: pnpm lint

      - name: Commit and Push
        run: |
          git config --local user.email "action-bot@github.com"
          git config --local user.name "GitHub Action bot"
          git commit -am "style: lint code" && git push || echo "No changes to commit"
